### ISSUE TITLE
No data showing

### ISSUE THREAD

**Issue by dsyme** [CompositionalIT/SAFE-Dojo#107]
I just went through the getting started steps but got no data showing.

I adjusted the firewall permissions for "server" to make sure it has public network access but I didn't get any difference

![image](https://user-images.githubusercontent.com/7204669/125619537-abc3336e-cc49-41a1-934e-b1e11748b913.png)

**Comment by dsyme** [comment]
I see, that's the point, IT'S A DOJO DON

**Comment by isaacabraham** [comment]
Yes. The same one that we did all those years ago in Skills Matter ;-)
