### ISSUE TITLE
Azure deploy instructions are a little out of date

### ISSUE THREAD

**Issue by dsyme** [CompositionalIT/SAFE-Dojo#111]
It's possible the Azure deploy should be removed from the Dojo but it's kind of great to have it there.

I did get it to work by

1. Installing the Azure CLI on this laptop that didn't have it
2. Renaming "new_app" in Build.fs

It's pretty cool that it's so simple, really amazing.

**Comment by isaacabraham** [comment]
We probably just need to add back in some readme instructions for deploying to Azure - one of the restrictions with naming in web apps is that you can't have an _ , but we could (should) add that into Farmer so it gives a nice error when you try to deploy.

**Comment by theprash** [comment]
I've improved the Azure deploy instructions a bit and also changed Build.fs:

```fsharp
    let web = webApp {
        name "TODO: Change this to a globally unique name containing only alphanumeric or hyphen characters"
```

https://github.com/CompositionalIT/SAFE-Dojo/commit/59c36f2e39549cb4099cd6dc047f5129c29490cc
