### ISSUE TITLE
Error 'Target "RunTests" is not defined' when running `dotnet run`

### ISSUE THREAD

**Issue by yoLotus** [CompositionalIT/SAFE-Dojo#115]
Hello,

I just pull `master` recently and did a `$ dotnet tool restore` then a `$ dotnet run` but the latest is giving the following error:

```
Target "RunTests" is not defined. Existing targets:
  - Clean
  - InstallClient
  - Bundle
  - Azure
  - Run
  - Format
``` 

I had to checkout before #114 PR to make it work (as it seems to remove the `RunTests` code).

I'm a newbie in F# and all its tools (that's why I'm trying SAFE-Dojo :), thx for the work by the way) so not sure what to do to help.

**Comment by isaacabraham** [comment]
Sorry about that, and thanks for reporting it. Give me 5 minutes to fix this :-)

**Comment by isaacabraham** [comment]
This was our (my) fault for blindly accepting that PR rather than testing it locally first. Fixed now - feel free to pull to latest and it should just work.

Sorry about that.

**Comment by yoLotus** [comment]
no problem, thanks you very much!

**Comment by yoLotus** [comment]
just tried, it works! 👍
