### ISSUE TITLE
First time setup instructions do not work

### ISSUE THREAD

**Issue by e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd** [CompositionalIT/SAFE-Dojo#118]
Cloning the repo and following the instructions does not work.
The instructions fail me at step 2; Running `dotnet restore`.

I had to run `dotnet run .\Build.fsproj Run` to get the project to work.
After running that command `dotnet run` without any arguments works for some reason.

In my opinion stuff like that is critical, if I were not really interested in SAFE I probably would not have bothered with figuring this out.

**Comment by isaacabraham** [comment]
Thanks for reporting this. We obviously want the dojo to be a great first time experience so are keen to fix issues like this.

It would certainly help to know what the error that you received was.

I hope you found the dojo enjoyable and fun to use, nonetheless.

**Comment by isaacabraham** [comment]
@Akash-Mair can you have a look at this?

**Comment by e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd** [comment]
This is the output I got after cloning the repo and follwing the instructions.
> ~> dotnet tool restore
Tool 'paket' (version '6.0.0-rc002') was restored. Available commands: paket
Tool 'fable' (version '3.2.1') was restored. Available commands: fable
Tool 'fantomas-tool' (version '4.4.0') was restored. Available commands: fantomas

> ~> dotnet restore
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.

Unfortunately I can no longer reproduce the `dotnet run` problem.

**Comment by Akash-Mair** [comment]
Thanks for pointing this out, I've removed the `dotnet restore` command from the readme as I don't believe it should be needed only a `dotnet tool restore` and a `dotnet run`
Please let me know if you face any other issues
I'll be closing this as removing the command should prevent others from running into this
