### ISSUE TITLE
Template / Dojo won't run out of the box

### ISSUE THREAD

**Issue by pw242** [CompositionalIT/SAFE-Dojo#119]
For both this project and the SAFE 'Quick Start' template, the project won't run out of the box. After following the instructions diligently I got an error:
Unexpected token {
This was in:
node_modules\p-limit\index.js:29
Which read
`} catch {}`
I changed this to
`} catch (err) {}`

On re-running I got a similar error in place:
node_modules\globby\index.js:28
After a similar fix, the project seemed to work and I could see the application on localhost:8080. However localhost:8085 still gives a 404 - not sure if that is intended or not?

Versions:
Node 8.11.3
dotnet 5.0.400

As an aside how do I get support on Slack?
https://functionalprogramming.slack.com/ does nothing for me - I can log in to slack, but no channel access.
Likewise I joined the F Sharp Foundation but have received no Slack invitation.

**Comment by theprash** [comment]
@pw242 I know this response is quite late now but I suspect this was from having quite an old version of node. Is this still an issue for you now? If so, feel free to re-open including any new details. I realise that the SAFE Template requirements say you need node v8+ but it's possible that's out of date.

Have you managed to join the F# Foundation Slack yet? After you create an account on the F# Foundation site you need to then click the button to actually join the foundation and only then are you a member and will receive the Slack invitation. It catches a lot of people out unfortunately!
