### ISSUE TITLE
metaweather.com is down

### ISSUE THREAD

**Issue by nick-gravgaard** [CompositionalIT/SAFE-Dojo#133]
I was just working through the dojo, but I ran into problems because [metaweather.com](http://metaweather.com) is down. I have no idea if it's ever going to come back online, but I suspect it won't. I'm going to review free weather APIs and see if I can find one which looks easy to switch the code to, and looks like it will be around for some time.

Edit: I've made a [PR which uses open-meteo instead](https://github.com/CompositionalIT/SAFE-Dojo/pull/134).

**Comment by ncryer** [comment]
Great work. As a newcomer to F# I was bummed that this tutorial didn't work out of the box.

**Comment by jonaskello** [comment]
I had the same experience, could not compile because the site was not up. Wouldn't it be better to just keep local files instead of relying on an external site being up in order to be able to compile?

**Comment by theprash** [comment]
#134 is merged now, which solves the problem. We just need to get the solution branch updated too so I'll leave this issue open to track that.

@jonaskello I kind of agree. I don't like being reliant on 3 external APIs to compile the app, never mind run it! And I would like the app to be meaningful to people outside the UK. Fixing those issues would mean effectively re-building it from scratch, which might be worth it if we can find the time to invest in it.

**Comment by theprash** [comment]
@jonaskello We've decided on an approach to mitigate APIs being down. I've opened two issues here: #137, #138

**Comment by theprash** [comment]
All done. Thanks again @nickgravgaard
