### ISSUE TITLE
Rename function for retrieving weather

### ISSUE THREAD

**Issue by bruinbrown** [CompositionalIT/SAFE-Dojo#15]
We currently have a function called getWeatherForPosition which retrieves the weather from the weather API which we tell people to use. Within our web API we also have a getWeatherForPosition function which is used to call the getWeatherForPosition API within the weather API. We should rename one of these to remove any possible confusion.

- [x] Update one of the function names
- [x] Update any documentation which references this function name
- [x] Retest dojo

**Comment by isaacabraham** [comment]
Linked to #18
