### ISSUE TITLE
Azure Deployment: Azure returns error 404

### ISSUE THREAD

**Issue by kumkee** [CompositionalIT/SAFE-Dojo#169]
After deploying to Azure without errors, I fail to visit the web app.
Is there anything on the Azure Dashboard I need to do after deployment?

Thank you,

### Update
After changing the `operating_system` to `Linux`
```fsharp
let web = webApp {
      name "kumkeesafe"
      operating_system Linux
      sku WebApp.Sku.F1
      runtime_stack Runtime.DotNet50
      zip_deploy "deploy"
      }
```
I got a new error 
> :( Application Error
If you are the application administrator, you can access the [diagnostic resources](https://kumkeesafe.scm.azurewebsites.net/detectors).

Here is supposedly the URL of my app https://kumkeesafe.azurewebsites.net/

**Comment by theprash** [comment]
Hi @kumkee. What exactly did you deploy? Was it the master branch as it is with no changes? Or did it include some of your own changes? If you deployed your own version, then what happens if you deploy the master branch as it is?

**Comment by kumkee** [comment]
> Hi @kumkee. What exactly did you deploy? Was it the master branch as it is with no changes? Or did it include some of your own changes? If you deployed your own version, then what happens if you deploy the master branch as it is?

With your reminder in mind, I tried deploying [with](https://github.com/kumkee/SAFE_Dojo) and [without](https://github.com/kumkee/SAFE_Dojo/tree/master) my answers to the dojo. Both return the 404 error. Please follow the links to inspect my codes.

**Comment by Tom-Sloboda** [comment]
@kumkee, as a sanity check could you go to the App Service in Azure, then go to [App Service Editor](https://stackoverflow.com/a/55245932) and check that the files have been deployed?

**Comment by kumkee** [comment]
> @kumkee, as a sanity check could you go to the App Service in Azure, then go to [App Service Editor](https://stackoverflow.com/a/55245932) and check that the files have been deployed?

I've removed the deployment and used Azure Functions instead. I couldn't wait a month.
I can try to reproduce the error however if you want to investigate the problem.

**Comment by isaacabraham** [comment]
@kumkee this might require a newer version of Farmer than what is bundled with the Dojo. There were previously some issues with Linux deployments with old Farmer versions.

**Comment by Tom-Sloboda** [comment]
Closing as no action required
