### ISSUE TITLE
SAFE-Dojo-master do not work 

### ISSUE THREAD

**Issue by MauryLoic** [CompositionalIT/SAFE-Dojo#172]
Hello,

I'am trying to run the application with dotnet run, unfortunately that do not work.
Here is the error :

client: ERROR in Module not found: Error: Can't resolve 'SAFE-Dojo-master\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=8080&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true' in 'SAFE-Dojo-master'

why ?

I'am on Windows 10, with dotnet sdk 6.0.408
nodejs: v18.16.0
npm: 9.5.1

Thank you

Loïc

**Comment by DragosIlies** [comment]
Hey Loïc, have you tried removing package-lock.json along with the node_modules folder and rerunning `dotnet run`?

**Comment by MauryLoic** [comment]
Hello Dragosllies,

I did, what you suggest, unfortunatelly that still do not work.

Before this error I have this :

client: <w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.
client: <i> [webpack-dev-server] Content not from webpack is served from 'SAFE-Dojo-master\src\Client\public' directory
client: <i> [webpack-dev-server] 404s will fallback to '/index.html'

and later the error, with webpack error.

It seem that webpack cannot compile ?

Thank you for your help

Loïc
