### ISSUE TITLE
MacOS and Port 5000

### ISSUE THREAD

**Issue by SpiralOSS** [CompositionalIT/SAFE-Dojo#178]
Error:
server: Unhandled exception. System.IO.IOException: Failed to bind to address http://0.0.0.0:5000: address already in use.

Fix:
https://apple.stackexchange.com/questions/431154/should-controlcenter-app-listen-to-port-5000-tcp-on-a-normal-macos-monterey-syst

I can add something to the troubleshooting section. I tried changing the port in-code to 5010 but was receiving 403 errors; so I'm not sure what the proper fix is (still learning).

**Comment by Larocceau** [comment]
Hi SpiralOSS. Thanks a lot for raising this ticket! I had a look into it; the ports address http://0.0.0.0/5000 should not be used here, it should be http:/localhost/5000. I created pull request #179 to fix this, and will get someone to review that ASAP.

**Comment by Larocceau** [comment]
@SpiralOSS the PR to fix this has been merged, please let us know if your issue is fully resolved, so we can close the issue.

**Comment by SpiralOSS** [comment]
Confirmed. I am no longer receiving the port-conflict error. Thank you!
