### ISSUE TITLE
"If using Visual Studio 2017, do NOT attempt to build directly in VS. You must use build.cmd to compile and run the application."

### ISSUE THREAD

**Issue by ovatsus** [CompositionalIT/SAFE-Dojo#24]
Is this something that can be fixed? Just seeing this will probably put off a bunch of people. Would be great if it can be made so you can just build inside VS

**Comment by isaacabraham** [comment]
You're right, this should be fixed. It might have just been the individuals at that dojo that experienced this - need to try it out.

Can you repro this issue?

**Comment by ovatsus** [comment]
Haven't tried it yet

On 12 Apr 2018 11:57, Isaac Abraham <notifications@github.com> wrote:

You're right, this should be fixed. It might have just been the individuals at that dojo that experienced this - need to try it out.

Can you repro this issue?
