### ISSUE TITLE
'Trying the Post Verb' instructions can lead to error in application

### ISSUE THREAD

**Issue by WalternativE** [CompositionalIT/SAFE-Dojo#26]
# What is the problem?

In `6. Trying the POST verb` under the section `On the Client` the instructions tell participants to use the `json` method on the response. In the case of the `WeatherResponse` type this will lead to a silent incomplete deserialization. The weather image will not be resolved correctly and the console will display an 404 Error because the discriminated union will yield an undefined value which is passed to the lookup call.

# How can it be resolved?

The following code snipped shows an example of the error condition as well as a possible solution.

```fsharp
let! weatherResponse  = Fetch.postRecord "/api/weather" { PostCode = postcode } []
 // let! weather = weatherResponse.json<WeatherResponse>()   This would not work correctly
let! weather = weatherResponse.text () |> Promise.map ofJson<WeatherResponse> //This does
```

Another way would to use `fetchAs` directly with the right set of properties. I'm not entirely sure how I would put this into the instructions. It might be best to have another POST call that exemplifies the usage, can be copied and adjusted.

What do you think?

**Comment by ponchoalv** [comment]
same error here.

**Comment by ponchoalv** [comment]
I finally do it this way:

First I defined a postRecord Wraper
```
[<AutoOpen>]
module RequestHelper =
        let [<PassGenerics>] postRequestAs<'T> uri requestData options =
            Fetch.postRecord uri requestData options 
                |> Promise.bind (fun fetched -> fetched.text()) 
                |> Promise.map ofJson<'T>
                
```

And Then I use the helper function like this:

```
 let! location = postRequestAs<LocationResponse> "api/distance" { Postcode = postcode } []

 let! crimes = postRequestAs<CrimeResponse array> "api/crime" { Postcode = postcode } []

 let! weather = postRequestAs<WeatherResponse> "api/weather" { Postcode = postcode } []
```

**Comment by isaacabraham** [comment]
apologies for the lack of response - will look into this shortly. thanks for pointing it out!

**Comment by isaacabraham** [comment]
@WalternativE @ponchoalv I've amended the readme to now direct people to use the correct mechanisms - thanks again for pointing this out (I only ever tested it with the non-DU endpoints, which always worked).
