### ISSUE TITLE
Support for Node 10

### ISSUE THREAD

**Issue by OnurGumus** [CompositionalIT/SAFE-Dojo#27]
If you have Node 10.x build fails as below:

Error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Running build failed.
Error:
System.Exception: 'C:\Program Files (x86)\Yarn\bin\yarn.cmd install --frozen-lockfile' failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.run(String cmd, String args, String workingDir) in D:\Projects\SAFE-Dojo-master\build.fsx:line 28
   at FSI_0005.Build.clo@34-2.Invoke(Unit _arg2) in D:\Projects\SAFE-Dojo-master\build.fsx:line 37
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626

**Comment by isaacabraham** [comment]
@theimowski does the template nowadays generate node-10.x compatible solutions?

**Comment by theimowski** [comment]
I haven't tested it with node 10. Looks like its Yarn <-> node compatibility issue

**Comment by WalternativE** [comment]
The problem stems from the `upath` dependency which is pulled in transitively via the webpack dev server. It's rather easy to resolve: just delete the yarn lock-file, start a `yarn install` to generate a new lock-file and use the `build.cmd` to run your project. In theory everything should still work as the dependencies are already stated explicitly in the package.json file. I'm currently investigating this. Is a more recent version of the lock-file something I could offer as a PR when I'm done testing, @isaacabraham?

**Comment by isaacabraham** [comment]
Sure, that would be great. As long as the dependencies are still backwards-compatible, that's great.

**Comment by WalternativE** [comment]
As far as I can tell they still are - unfortunately I'm currently experiencing problems with node 8.x LTS on my machine - I'll set up a VM tomorrow and verify it with this setup.

**Comment by voronoipotato** [comment]
I did 

```bash
yarn upgrade webpack
```

Seems to fix the problem.

https://github.com/airbnb/enzyme/issues/1637

**Comment by fergusmeiklejohn** [comment]
The build is still failing out the box
`yarn upgrade` fixes it

Perhaps we should add this as a first time build step in the readme?  I worry this sort of thing puts newcomers off

**Comment by isaacabraham** [comment]
Ouch. Sorry - Didn't realise this is fixed. I'll accept that PR now!
