### ISSUE TITLE
Issues surrounding global.json file

### ISSUE THREAD

**Issue by bruinbrown** [CompositionalIT/SAFE-Dojo#30]
I ran the dojo in Southampton the other week, the dojo was mostly successful but the vast majority of attendees ran into issues surrounding the global.json file containing a mismatched .Net core version then the one installed on the user's machine. This was caused by people installing newer versions of .Net core than the version used in the dojo. The solution was to change the version number specified in the global.json file to the version specified when running ```dotnet --version``` outside of the project directory.

Given that the issue is solved by changing the version specified in the file, is there any point in keeping the global.json file since people will need to change the version number anyway?

**Comment by slifin** [comment]
On a fresh install with up to date tools, I first hit this issue: https://github.com/CompositionalIT/SAFE-Dojo/issues/27 and then this issue

So far the workarounds have been to delete yarn.lock and global.json then run ./build.sh

**Comment by isaacabraham** [comment]
@bruinbrown happy for us to remove the global.json file - I'm still not convinced that that file helps more than it hinders anyway.

**Comment by isaacabraham** [comment]
I think that this is the way SAFE is going in general - @bruinbrown happy for you to remove.
