### ISSUE TITLE
Keyboard Focus when changing Postcode

### ISSUE THREAD

**Issue by xdaDaveShaw** [CompositionalIT/SAFE-Dojo#38]
When typing in a postcode the focus is always set to the end of the text box.

![gif](https://user-images.githubusercontent.com/2511715/43167436-8b07de1a-8f91-11e8-8489-e092d04ed633.gif)

This looks to be because changing the text goes through the update loop and sets the text to upper-case, which in turn updates the text moving the selection to the end.

I've had a look at fixing this by setting `selectionStart` and `selectionEnd` in the view, but I can't get it to work properly.

**Comment by xdaDaveShaw** [comment]
I meant to say last night when I logged this... I'm more interested in how this _might_ be fixed, than actually seeing it fixed.

Would the PostcodeChanged event updating the Postcode be removed and using plain old javascript or a CSS text transform, or is there a React / Fable / Elmish way to do it.

**Comment by xdaDaveShaw** [comment]
Looks related to: https://github.com/elmish/react/issues/12

**Comment by isaacabraham** [comment]
Mmmm. Probably the way you would have to do it is manually figure out the index of which key had changed, and then on the way out set the index of the textbox in the view function. I'm not sure how to do that off the top of my head though! Happy to see what the other issue solution is :-)

**Comment by xdaDaveShaw** [comment]
Looking at the comments on that linked Issue, it would be solved in the next version of Elmish React or by using `withReactUnoptimized` - I'm unable to test at the moment, but might have time later tonigh.

**Comment by xdaDaveShaw** [comment]
Hmm, `withReactUnoptimized` doesn't seem to solve it. Maybe the newer Elmish React will when it is released

**Comment by isaacabraham** [comment]
Fixed with latest PR.
