### ISSUE TITLE
Debugging on VSCode

### ISSUE THREAD

**Issue by slifin** [CompositionalIT/SAFE-Dojo#40]
When using the dojo is it possible to use a debugger on VSCode to inspect what is happening?

After adding a breakpoint and pressing the play button the following message was displayed:
```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```

**Comment by isaacabraham** [comment]
Hi @slifin yes it should be - I'll have a look this week at adding this to the documenation, either in the dojo directly or on the SAFE docs site.

**Comment by isaacabraham** [comment]
I've made a couple of changes so that you can hit CTRL+SHIFT+B to build + launch the client and server, whilst F5 will try to attach to both processes for debugging. I think there's an issue with the source maps for the client, but the server-side debugging seems to be working.

**Comment by isaacabraham** [comment]
@bruinbrown does the latest upgrade the to dojo include last SAFE feature for deubgging?

**Comment by isaacabraham** [comment]
Fixed with latest updates.
