### ISSUE TITLE
Example Postcodes

### ISSUE THREAD

**Issue by bruinbrown** [CompositionalIT/SAFE-Dojo#42]
Some people might not know English postcodes by heart, so here's a selection

EC2A 4NE
E1 7QA
NG7 4ED
WD6 1FY
N15 6AX
NW4 2PJ

Please add more for a wider selection

**Comment by theprash** [comment]
Let's put these right into the app UI.

**Comment by theprash** [comment]
Done 😊
![image](https://user-images.githubusercontent.com/1362490/187730605-4ccdfbf7-5117-445f-b4d7-d4f21394cb86.png)
