### ISSUE TITLE
API url only returns an empty list

### ISSUE THREAD

**Issue by voronoipotato** [CompositionalIT/SAFE-Dojo#44]
https://data.police.uk/api/crimes-street/all-crime?lat=51.5074&lng=0.1278

Is there perhaps a more reliable development friendly API to pull from?

**Comment by diminou** [comment]
There is a workaround - adding the date parameter to the query. However, the date should be fairly far into the past. For instance, [https://data.police.uk/api/crimes-street/all-crime?lat=51.5074&lng=0.1278&date=2017-09](https://data.police.uk/api/crimes-street/all-crime?lat=51.5074&lng=0.1278&date=2017-09) works.

**Comment by theprash** [comment]
Seems to be working again. Thanks for pointing it out, though 👍🏾
