### ISSUE TITLE
README needs amending, the project won't build on Mac

### ISSUE THREAD

**Issue by fergusmeiklejohn** [CompositionalIT/SAFE-Dojo#45]
MacOSX
`build.sh run` returns: `bash: build.sh: command not found`

**Comment by pmn** [comment]
@fergusmeiklejohn just ran it successfully here (macOS High Sierra, dotnet version 2.2.101). Just to be safe, you ran `./build.sh run` and not `build.sh run`, correct?

**Comment by fergusmeiklejohn** [comment]
Ah of course that's the problem! I've made a pull request to changeth readme to `./build.sh`

Big Picture: we need one agreed way to build across all Fable projects

**Comment by isaacabraham** [comment]
The Fable template is being deprecated in place of the SAFE one which will go a long way to helping make a more consistent story in this regard.
