### ISSUE TITLE
Unable to run FAKE on OSX Mojave

### ISSUE THREAD

**Issue by Kavignon** [CompositionalIT/SAFE-Dojo#54]
I'm trying run the fake build script, but I can't on a Mac.

```
Consider adding your dependencies via `#r` dependencies, for example add '#r "paket: nuget FSharp.Core //"'.
See https://fake.build/fake-fake5-modules.html for details. 
If you know what you are doing you can silence this warning by setting the environment variable 'FAKE_ALLOW_NO_DEPENDENCIES' to 'true'
Updating group Main in /Users/sinroscale/SAFE-Dojo/.fake/build.fsx/paket.dependencies
Resolving packages for group Main:
 - FSharp.Core 4.6.2
Locked version resolution written to /Users/sinroscale/SAFE-Dojo/.fake/build.fsx/paket.lock
Extracted Paket.Restore.targets to: /Users/sinroscale/SAFE-Dojo/.fake/build.fsx/.paket/Paket.Restore.targets
Starting full restore process.
Script is not valid:
	/Users/sinroscale/SAFE-Dojo/build.fsx (1,0)-(1,43): Error FS0078: Unable to find the file 'packages/build/FAKE/tools/FakeLib.dll' in any of
	 /Users/sinroscale/.nuget/packages/netstandard.library/2.0.3/build/netstandard2.0/ref
	 /Users/sinroscale/SAFE-Dojo
	 /Users/sinroscale/.dotnet/tools/.store/fake-cli/5.13.2/fake-cli/5.13.2/tools/netcoreapp2.1/any/
```

**Comment by isaacabraham** [comment]
@Kavignon how are you running the fake script?
@bruinbrown can you test this out?

**Comment by Kavignon** [comment]
I ran this line in the Terminal app: "`fake build -t Run`"

**Comment by isaacabraham** [comment]
I'm baffled by this one. On the one hand I can see that the fake 5 global tool is being used here, but at the same time the errors seem to suggest an old FAKE 4 script is being used. Are you sure you're on the latest master branch? Or are you in another branch?

**Comment by isaacabraham** [comment]
It also looks like from here that a lock file is being generated - again, something fishy is happening here. @matthid am I right in what I'm thinking here?

**Comment by matthid** [comment]
Yes without having the script contents it is guessing ;)

**Comment by Kavignon** [comment]
Yes, I'm using the master branch.

**Comment by isaacabraham** [comment]
@Kavignon which commit are you on? The fake script in the latest commit is a FAKE 5 script, so you shouldn't be seeing this error. @bruinbrown can you just test this on your macbook to check that everything is ok?
