### ISSUE TITLE
Step 6, change endpoint to post is very challenging

### ISSUE THREAD

**Issue by jackfoxy** [CompositionalIT/SAFE-Dojo#56]
Last exercise (change endpoint to post) was especially challenging. (6i) "Create a new PostcodeRequest record..." threw me off. Got it working without using that new record, and never figured its purpose.

**Comment by paytonrules** [comment]
I found the directions to be very confusing - particularly because they say "don't use `json`" on the response, and then the suggested solution does exactly that.

**Comment by isaacabraham** [comment]
Agreed. We should either fix or remove this exercise. I've got some OSS time this week so I'll do it then.

**Comment by jackfoxy** [comment]
Fix. It is a good exercise and the results teach.

**Comment by isaacabraham** [comment]
I've pushed to master with a few changes to documentation, and updated the suggested solution based off of latest master (it was neglected and out of sync - hence the misleading `json` function).

Can either of you give it a quick look through and see if it looks better now?

**Comment by jackfoxy** [comment]
I'll try to get to it tonight. @isaacabraham

**Comment by jackfoxy** [comment]
@isaacabraham  instruction appear clear and suggested result looks reasonable.

**Comment by jackfoxy** [comment]
Off topic: 
I'm not a fan of the FAKE 5 runner. Could be selection bias, but every other F# OSS repo I clone works with .\build, not the runner. 
Ctrl-C appears to end my run session from Powershell, but not really. I suspect the process is still running. My Powershell session is crippled.

**Comment by paytonrules** [comment]
Worked much better for me as well.

**Comment by isaacabraham** [comment]
Thanks for feedback @paytonrules @jackfoxy - much appreciated.
