### ISSUE TITLE
Help with using Decode.Auto.unsafeFromString

### ISSUE THREAD

**Issue by DavidSSL** [CompositionalIT/SAFE-Dojo#60]
Hi,

In the instructions we're told to:

> Notice that the return type is different though when using postRecord. To get the data returned from the server you can use a combination text method on the response and the Decode.Auto.unsafeFromString<'T> function to safely retrieve the typed result from the server

From the response I am able to call .text() which returns a Promise<string>. Since I have absolutely no idea about Fable or JS Promises, and looking at the signature of Decode.Auto.unsafeFromString<'T>, I am now a bit stuck until I can fill the gap in my knowledge. 

So, I tried to look at the "suggested-solution" branch but that actually uses .json which in the instructions we're told not to. 

Can anyone shed some light on this?

Regards,

David

**Comment by isaacabraham** [comment]
Hi David. I thought we'd fixed this with #56 :-( @paytonrules any thoughts?

**Comment by DavidSSL** [comment]
Hi @isaacabraham. Thanks for getting back to me. I think it was my fault in so far as looking at the suggested solution! I guess that I didn't get the latest changes from upstream and hence I was seeing .json() in my local repo. 

Sorry about that.

**Comment by isaacabraham** [comment]
The suggested solution should have been updated as well :-) I'll double check that.
