### ISSUE TITLE
Client App > Postcode is null and cause an error in the console

### ISSUE THREAD

**Issue by Nordes** [CompositionalIT/SAFE-Dojo#77]
**Error:**

> Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
>     in input (created by Elmish_HMR_Common_Components_LazyView)
>     in div (created by Elmish_HMR_Common_Components_LazyView)
>     in div (created by Elmish_HMR_Common_Components_LazyView)
>     in div (created by Elmish_HMR_Common_Components_LazyView)
>     in section (created by Elmish_HMR_Common_Components_LazyView)
>     in Elmish_HMR_Common_Components_LazyView

**Proposed Solution**
Instead of having `null` assigned to the postcode at the beginning (since we should never use null anyway), we can assign an empty string. An another solution would be to create an option string type for postal code. This would allow the `Some/None` thing.

Lazy solution
```fsharp
let init () =
    { Postcode = "" // <=== null to empty string
      Report = None
      ValidationError = None
      ServerState = Idle }, Cmd.ofMsg (PostcodeChanged "")
```

**Comment by isaacabraham** [comment]
Seems reasonable - could you submit a PR for this? :-)
