### ISSUE TITLE
Unable to run in Visual Studio Code with F5

### ISSUE THREAD

**Issue by Dzeneralen** [CompositionalIT/SAFE-Dojo#83]
First off, thank you for creating the Dojo. Looking forward to try it out. 

I encountered an issue in Visual Studio Code on Windows where the term 'fake' was not recognized when running the configuration "Watch SAFE App". I could run `dotnet tool restore` and `dotnet fake build` without any issues.

> The term 'fake' is not recognized as the name of a cmdlet, function, script file, or operable program.

To resolve the issue I installed FAKE globally with `dotnet tool install fake-cli -g`. When this was done I could run the "Watch SAFE App" configuration without issues.

Is this an issue only I encountered, or should we add a notification in the readme mentioning it for new users unfamiliar with FAKE?

**Comment by isaacabraham** [comment]
Hmmmm. What version of .NET Core do you have?

On .NET Core 3.1, running `dotnet tool restore` should automatically bring down FAKE, after which you should be able to run the second command.

**Comment by Dzeneralen** [comment]
I have SDK 3.1.301 installed. `dotnet tool restore` did fetch fake for me, and it was available from `dotnet fake <command>`, but the configuration set up for VS Code could not recognize it until it was installed globally.

**Comment by isaacabraham** [comment]
Ah. We probably just need to make some small changes to the script then.
