### ISSUE TITLE
SAFE Dojo opens blank page with Microsoft.AspNetCore.Hosting.Diagnostics [2] Request returning 404

### ISSUE THREAD

**Issue by gsorensen** [CompositionalIT/SAFE-Dojo#93]
Hi, I've been trying to work through the SAFE dojo, but the launched site obtained from the cloned repo results in a request returning 404. I've tried running the app both in Safari and Firefox.

My MacBook (Intel-based) currently has the following 
- .NET Core 3.1.404
- npm 6.14.10
- Node v14.15.4
and I am developing in VS Code with the Ionide extension, as per the instructions given in the README.

I am able to run ```dotnet tool restore```followed by ```dotnet fake build``` without any issues (Though one thing worth noting is npm did complain about some vulnerabilities which I fixed with ```npm audit fix```) and the app is said to be hosted on localhost:8085, but whenever I launch the page Microsoft.AspNetCore.Hosting.Diagnostics [2] returns its request with 404 and as such I am only seeing a blank page.

From the instructions I should be seeing the search bar, but no such luck. I would assume a clean, newly cloned repo would function as intended so I am a bit at loss as to what would be wrong. I do see that since the time the instructions were written, the port was changed from 8080 to 8085, are there any other changes one need to take into account in order to run the dojo at this point?

Kind regards, 

Glen

**Comment by isaacabraham** [comment]
Hi @gsorensen - apologies for only seeing this now, six months later. We're going to rebuild the Dojo on SAFE 3 in the next week or two to see what's happening. I'm assuming that this was environmental as I've not heard of other reports of this but once it's re-released please do try again.

**Comment by gsorensen** [comment]
Hello, yes, that did appear to be the case. When I ran the Dojo on my Windows desktop the first time, a couple of permissions related to the firewall were asked for and after filling these out, I was able to run the dojo website locally as described.
